package MessageBoard;


/**
* MessageBoard/MessagePostBoxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from message_board.idl
* Saturday, October 21, 2017 8:15:54 AM MSK
*/

public interface MessagePostBoxOperations 
{
  String getVersion ();
  void putMessage (String from, String message);
} // interface MessagePostBoxOperations
